- name: Install mysql Library
  ansible.builtin.pip:
    name: "{{ item }}"
    executable: pip3.9
  loop:
  - PyMySQL
  - cryptography

- name: install mysql-server
  ansible.builtin.dnf:
    name: mysql-server
    state: installed

- name: start and enable mysql-server service
  ansible.builtin.service:
    name: mysqld
    state: started
    enabled: yes

- name: connect to mysql-server
  community.mysql.mysql_info:
    login_user: "{{ MYSQL_USER }}"
    login_password: "{{ MYSQL_PASSWORD }}"
    login_host: mysql.pavancloud9.online
  register: mysql_info_command_result
  ignore_errors: true

# - name: print the output
#   ansible.builtin.debug:
#     msg: "{{ mysql_info_command_result }}"

- name: set mysql-server root password
  ansible.builtin.command:  " mysql_secure_installation --set-{{ root }}-pass {{ MYSQL_PASSWORD }}"
  when: mysql_info_command_result.failed is true